fix: Correct the path of service account in google drive settings
bellingcat/auto-archiver pull request #123
Opened 2024-01-27 05:57 UTC by andyfcx

The functionality using GDrive with service account is not working, due to loading coinfig from the yaml is not right.

2024-01-31 09:59 UTC, djhmateer commented
Hi @andyfcx  On a tangent.. If you're using the service account strategy for Google Drive (which I did for a while), watch out for the 15GB limit. I made some notes here: https://davemateer.com/2022/04/28/google-drive-with-python

I switched over to OAuth.

Thanks for submitting a PR!

2024-02-01 12:46 UTC, msramalho commented on src/auto_archiver/storages/gd.py
> +            gd_service_account = config['gdrive_storage']['service_account']
```suggestion
            gd_service_account = self.service_account
```
This is actually the standard way of accessing the `configs` via `self`.

2024-02-01 12:47 UTC, msramalho commented on src/auto_archiver/storages/gd.py
> -    def upload(self, media: Media, **kwargs) -> bool:
great catch, this is the local_storage code.

2024-02-01 12:47 UTC, msramalho commented on src/auto_archiver/storages/gd.py
> +            gd_service_account = self.service_account
I've fixed the referencing here

2024-02-01 12:48 UTC, msramalho requested changes
only pending thing is explaining line 153, otherwise ready to go.

2024-02-01 13:35 UTC, andyfcx commented on src/auto_archiver/storages/gd.py
> +            items = self.service.ListFile(query_string).GetList()
Ah, sorry, this line is unnecessary.

2024-02-01 15:02 UTC, merged

2024-02-01 15:12 UTC, msramalho commented
code is released in 0.8.1: https://pypi.org/project/auto-archiver/

2024-11-10 16:53 UTC, knigady commented
gd.py cannot find the folder on Google Drive with the ID specified in the orchestration.yaml file, and as a result, it sets the value to None and uploads the file to the root of the drive. What could this be related to?